prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@application/shared_components/pwa/shortcuts/wilma.sql
@@application/shared_components/workflow/workflows/roi_workflow.sql
@@application/shared_components/navigation/lists/navigation_menu.sql
@@application/shared_components/navigation/lists/navigation_bar.sql
@@application/shared_components/navigation/lists/drawer_menu.sql
@@application/shared_components/navigation/lists/side_menu_bar.sql
@@application/shared_components/navigation/lists/application_configuration.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/app_105_logo_png.sql
@@application/shared_components/files/css_wm_style_css.sql
@@application/shared_components/files/images_wilma_logo_square_png.sql
@@application/shared_components/files/images_facebook_5968764_png.sql
@@application/shared_components/files/images_instagram_2111463_png.sql
@@application/shared_components/files/icons_filter_icon_png.sql
@@application/shared_components/files/icons_filter_icon_svg.sql
@@application/shared_components/files/icons_filter_icon_2_svg.sql
@@application/shared_components/files/icons_filter_svg.sql
@@application/shared_components/files/javascript_scrolling_effects_js.sql
@@application/shared_components/files/javascript_scrolling_effects_min_js.sql
@@application/shared_components/files/css_wm_home_style_css.sql
@@application/shared_components/files/pwa_shortcut_icon_10_png.sql
@@application/shared_components/files/css_wm_style_min_css.sql
@@application/shared_components/files/css_wm_home_style_min_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/administration_rights.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/load_gcp_api_key.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/list/wm_side_navigation_menu.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/email/templates/new_customer_acknowledgement_email.sql
@@application/shared_components/email/templates/new_customer_registration.sql
@@application/shared_components/email/templates/follow_up_email.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/oracle_db_user_account.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00002.sql
@@application/pages/page_00003.sql
@@application/pages/page_00004.sql
@@application/pages/page_00005.sql
@@application/pages/page_00010.sql
@@application/pages/page_09999.sql
@@application/pages/page_10010.sql
@@application/deployment/definition.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
