name: Query SYSDATE from Oracle Autonomous DB

on: [push]
permissions:
  contents: read 
jobs:
  query-sysdate:
    environment: Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Public Repo
        uses: actions/checkout@v4
        
      - name: Print variables
        run: |
          echo ${{ vars.WALLET_REPO_PAT }}
          
      - name: Checkout private wallet repo
        uses: actions/checkout@v4
        with:
          repository: ChkBuk/secretsrepo
          path: oci_wallet
          token: "${{ vars.WALLET_REPO_PAT }}"

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Install SQLcl
        run: |
          curl -L -o sqlcl.zip https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
          unzip sqlcl.zip -d sqlcl

      - name: Debug wallet folder contents
        run: |
          echo "Listing contents of oci_wallet and HOME/wallet:"
          ls -R oci_wallet || true
          ls -R $HOME/wallet || true

      - name: Configure Wallet
        run: |
          echo "Copying wallet files..."
          mkdir -p "$HOME/wallet"
          cp -r oci_wallet/oci_wallet/* "$HOME/wallet/"
          echo "List $HOME/wallet content:"
          ls -R "$HOME/wallet"
          echo "Editing sqlnet.ora..."
          sed -i 's|?/network/admin|\$TNS_ADMIN|g' "$HOME/wallet/sqlnet.ora"
        shell: bash

      - name: Set Env Variables
        run: |
          echo "TNS_ADMIN=$HOME/wallet" >> $GITHUB_ENV
          echo "PATH=$PATH:$(pwd)/sqlcl/bin" >> $GITHUB_ENV

      - name: Query SYSDATE
        run: |
          echo "SELECT SYSDATE FROM DUAL;" > query.sql
          sql ${DB_USER}/${DB_PASSWORD}@${DB_ALIAS} @query.sql

        env:
          DB_USER: "ADMIN"
          DB_PASSWORD: "MahindaCollege2000!"
          DB_ALIAS: "1522/ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com"
