name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        
    - name: Deploy APEX App
      env:
        ORACLE_USER: "ADMIN"
        ORACLE_PASSWORD: "MahindaCollege2000!"
        ORACLE_HOST: "adb.ap-melbourne-1.oraclecloud.com"
        ORACLE_PORT: "1522"
        ORACLE_SERVICE: "ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com"
      run: |
        echo "Attempting connection to Oracle database..."
        echo "Using host: $ORACLE_HOST"
        echo "Using port: $ORACLE_PORT"
        echo "Using service: $ORACLE_SERVICE"
        
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v $ORACLE_USER/$ORACLE_PASSWORD@"(description=(address=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))" <<EOF
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        @f105/install.sql
        exit;
        EOF
