name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        

    
    - name: Run Installation
      run: |
        echo "===== PHASE 1: Verify Files ====="
        echo "Current directory: $(pwd)"
        ls -la f105/install.sql
    
        echo "===== PHASE 2: Test Connection ====="
        CONN="admin/MahindaCollege2000!@(description=(address=(protocol=tcps)(host=adb.ap-melbourne-1.oraclecloud.com)(port=1522))(connect_data=(service_name=ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com)))"
        
        # Simple test query
        echo "SELECT 'CONNECTED_AT:'||TO_CHAR(SYSDATE,'HH24:MI:SS') FROM dual;" | \
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "$CONN"
    
        echo "===== PHASE 3: Run Install Script ====="
        cat << 'EOF' > run_install.sql
        SET ECHO ON
        SET FEEDBACK ON
        SET SERVEROUTPUT ON SIZE UNLIMITED
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        
        PROMPT === PRE-INSTALL CHECK ===
        SELECT USER FROM dual;
        SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM dual;
        
        PROMPT === RUNNING INSTALL.SQL ===
        @f105/install.sql
        
        PROMPT === POST-INSTALL CHECK ===
        SELECT 'COMPLETED_AT:'||TO_CHAR(SYSDATE,'HH24:MI:SS') FROM dual;
        EXIT;
        EOF
    
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "$CONN" @run_install.sql 2>&1 | tee install.log
        echo "===== INSTALLATION OUTPUT ====="
        cat install.log
