name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        
    - name: Run SQL with Guaranteed Output
      run: |
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l $ORACLE_USER/$ORACLE_PASSWORD@"(description=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))" <<EOF > sql_output.log
        /* CRITICAL SETTINGS */
        set feedback on
        set heading on
        set sqlformat ansiconsole
        set serveroutput on size unlimited format wrapped
        
        /* SIMPLE TEST QUERY */
        SELECT 
            'SYSDATE:' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS date_output,
            'DATABASE:' || (SELECT name FROM v\$database) AS db_info
        FROM dual;
        
        EXIT;
        EOF
        
        echo "---- RAW OUTPUT ----"
        cat sql_output.log

    - name: Full Diagnostic
      run: |
        echo "---- SQLCL VERSION ----"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
        echo "---- ENV VARIABLES ----"
        printenv | grep ORACLE
        
        echo "---- CONNECTION TEST ----"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l $ORACLE_USER/$ORACLE_PASSWORD@"(description=(address=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))" <<EOF
        set feedback on
        set timing on
        SELECT 1+1 AS test_result FROM dual;
        EXIT;
        EOF
        
    - name: Upload Log
      uses: actions/upload-artifact@v4
      with:
        name: sql-results
        path: sql_output.log
