name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        
    - name: Deploy APEX App
      env:
        ORACLE_USER: ${{ secrets.DB_USER }}
        ORACLE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
        ORACLE_PORT: ${{ secrets.ORACLE_PORT }}
        ORACLE_SERVICE: ${{ secrets.ORACLE_SERVICE }}
    
    - name: Run Installation Script
      run: |
        echo "===== Starting Installation ====="
        
        # 1. First verify SQLcl can run simple queries
        echo "Testing basic SQLcl functionality..."
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "admin/MahindaCollege2000!@(description=(address=(protocol=tcps)(host=adb.ap-melbourne-1.oraclecloud.com)(port=1522))(connect_data=(service_name=ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com)))" <<EOF
        SET FEEDBACK ON
        SET SERVEROUTPUT ON
        SELECT 'SQLCL WORKS: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM dual;
        EXIT;
        EOF
        
        # 2. Create complete wrapper script
        cat << 'SQL_EOF' > wrapper.sql
        SET ECHO ON
        SET FEEDBACK ON
        SET SERVEROUTPUT ON SIZE UNLIMITED
        SET SQLFORMAT ANSICONSOLE
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        
        PROMPT [DEBUG] Current directory:
        HOST pwd
        PROMPT [DEBUG] Install script contents:
        HOST cat f105/install.sql
        PROMPT [DEBUG] Starting execution:
        
        @f105/install.sql
        
        PROMPT [DEBUG] Script completed
        SELECT 'COMPLETED_AT: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM dual;
        EXIT;
        SQL_EOF
        
        # 3. Execute with full debugging
        echo "===== Running Installation ====="
        CONN_STRING="(description=(retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-melbourne-1.oraclecloud.com))(connect_data=(service_name=ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "admin/MahindaCollege2000!@$CONN_STRING" @wrapper.sql 2>&1 | tee install.log
        
        echo "===== Final Output ====="
        cat install.log
