name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        

    
    - name: Run Installation with Full Debugging
      run: |
        echo "===== PHASE 1: Environment Verification ====="
        echo "Current directory: $(pwd)"
        echo "Java version: $(java -version 2>&1 | head -1)"
        echo "SQLcl path: $(which sql || echo 'Not in PATH')"
        ls -la ${GITHUB_WORKSPACE}/sqlcl/bin/sql
        ls -la f105/install.sql
    
        echo "===== PHASE 2: Direct Connection Test ====="
        CONN="admin/MahindaCollege2000!@(description=(address=(protocol=tcps)(host=adb.ap-melbourne-1.oraclecloud.com)(port=1522))(connect_data=(service_name=ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com)))"
        
        # Test with simple SQL file
        echo "SELECT 'DIRECT_TEST:'||TO_CHAR(SYSDATE,'HH24:MI:SS')||' USER:'||USER FROM dual;" > test.sql
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "$CONN" @test.sql 2>&1 | tee test.log
        echo "===== TEST OUTPUT ====="
        cat test.log
    
        echo "===== PHASE 3: Full Installation ====="
        cat << 'EOF' > debug_wrapper.sql
        SET ECHO ON
        SET FEEDBACK ON
        SET SERVEROUTPUT ON SIZE UNLIMITED
        SET SQLFORMAT ANSICONSOLE
        SET VERIFY ON
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        
        PROMPT === PRE-EXECUTION DEBUG ===
        HOST echo "Current dir: $(pwd)"
        HOST echo "SQLcl path: $(which sql)"
        SELECT 'START_TIME:'||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FROM dual;
        
        PROMPT === SCRIPT CONTENTS ===
        HOST cat f105/install.sql
        
        PROMPT === EXECUTION START ===
        @f105/install.sql
        
        PROMPT === EXECUTION COMPLETE ===
        SELECT 'END_TIME:'||TO_CHAR(SYSDATE,'YYYY-MM-DD HH24:MI:SS') FROM dual;
        EXIT;
        EOF
    
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "$CONN" @debug_wrapper.sql 2>&1 | tee install.log
        echo "===== FULL INSTALLATION OUTPUT ====="
        cat install.log
