name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        
    - name: Deploy APEX App
      env:
        ORACLE_USER: ${{ secrets.DB_USER }}
        ORACLE_PASSWORD: ${{ secrets.DB_PASSWORD }}
        ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
        ORACLE_PORT: ${{ secrets.ORACLE_PORT }}
        ORACLE_SERVICE: ${{ secrets.ORACLE_SERVICE }}
      run: |
        echo "===== Starting Installation ====="
        echo "Host: $ORACLE_HOST, Service: $ORACLE_SERVICE"
        
        # Create a wrapper script with output settings
        cat << 'SQL_EOF' > run_install.sql
        SET ECHO ON
        SET FEEDBACK ON
        SET SERVEROUTPUT ON SIZE UNLIMITED
        SET SQLFORMAT ANSICONSOLE
        SET VERIFY ON
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        
        -- Add timing information
        PROMPT Starting script execution at: 
        SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM dual;
        
        @f105/install.sql
        
        PROMPT Script completed at:
        SELECT TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') FROM dual;
        EXIT;
        SQL_EOF
        
        # Execute with forced output
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l admin/MahindaCollege2000!@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.ap-melbourne-1.oraclecloud.com))(connect_data=(service_name=ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))" @run_install.sql 2>&1 | tee install_output.log
        
        echo "===== Installation Output ====="
        cat install_output.log
