name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      ORACLE_USER: ${{ secrets.ORACLE_USER }}
      ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
      ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
      ORACLE_PORT: ${{ secrets.ORACLE_PORT }}
      ORACLE_SERVICE: ${{ secrets.ORACLE_SERVICE }}
      NLS_LANG: AMERICAN_AMERICA.AL32UTF8
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        
    - name: Run SQL with Guaranteed Output
      run: |
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l $ORACLE_USER/$ORACLE_PASSWORD@"(description=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))" <<EOF > sql_output.log
        /* CRITICAL SETTINGS */
        set feedback on
        set heading on
        set sqlformat ansiconsole
        set serveroutput on size unlimited format wrapped
        
        /* SIMPLE TEST QUERY */
        SELECT 
            'SYSDATE:' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS date_output,
            'DATABASE:' || (SELECT name FROM v\$database) AS db_info
        FROM dual;
        
        EXIT;
        EOF
        
        echo "---- RAW OUTPUT ----"
        cat sql_output.log

    - name: Full Diagnostic (Fixed)
      env:
        NLS_LANG: AMERICAN_AMERICA.AL32UTF8
      run: |
        echo "===== ENVIRONMENT ====="
        printenv | grep -E 'ORACLE|PATH|JAVA|SQLCL' || echo "No relevant env vars"
        
        echo "===== CONNECTION TEST ====="
        CONN_STRING="(description=(address=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))"
        echo "SELECT 1+1 AS test FROM dual;" | \
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l $ORACLE_USER/$ORACLE_PASSWORD@"$CONN_STRING" | tee sql_test.log
        
        echo "===== RESULTS ====="
        cat sql_test.log || echo "No output file generated"
