name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        

    
    - name: Debug Installation
      run: |
        echo "===== PHASE 1: Verify Files ====="
        echo "Current directory: $(pwd)"
        echo "SQLcl version:"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -version
        echo "Install script exists:"
        ls -la f105/install.sql || echo "MISSING"
    
        echo "===== PHASE 2: Test Minimal Connection ====="
        CONN="admin/MahindaCollege2000!@(description=(address=(protocol=tcps)(host=adb.ap-melbourne-1.oraclecloud.com)(port=1522))(connect_data=(service_name=ga8e55f0b539d22_sldevdb_high.adb.oraclecloud.com)))"
        echo "SELECT 'CONNECTION_SUCCESS:'||TO_CHAR(SYSDATE,'HH24:MI:SS') FROM dual;" | \
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v -l "$CONN"
    
        echo "===== PHASE 3: Run With Full Debug ====="
        cat << 'EOF' > debug.sql
        SET ECHO ON
        SET FEEDBACK ON
        SET SERVEROUTPUT ON SIZE UNLIMITED
        WHENEVER SQLERROR CONTINUE
        
        PROMPT === DATABASE INFO ===
        SELECT * FROM v$version;
        
        PROMPT === SCRIPT LOCATION ===
        HOST echo "PWD: $(pwd)" && ls -la f105/install.sql
        
        PROMPT === SCRIPT CONTENTS ===
        HOST cat f105/install.sql
        
        PROMPT === EXECUTION START ===
        @f105/install.sql
        
        PROMPT === EXECUTION END ===
        SELECT 'FINISHED_AT:'||TO_CHAR(SYSDATE,'HH24:MI:SS') FROM dual;
        EXIT;
        EOF
        
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -debug -v -l "$CONN" @debug.sql 2>&1 | tee debug.log
        echo "===== FULL DEBUG OUTPUT ====="
        cat debug.log
