name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "::add-path::$(pwd)/sqlcl/bin"  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl version:"
        $(pwd)/sqlcl/bin/sql -v
        
    - name: Deploy APEX App
      env:
        ORACLE_USER: ${{ secrets.ORACLE_USER }}
        ORACLE_PASSWORD: ${{ secrets.ORACLE_PASSWORD }}
        ORACLE_HOST: ${{ secrets.ORACLE_HOST }}
        ORACLE_PORT: ${{ secrets.ORACLE_PORT }}
        ORACLE_SERVICE: ${{ secrets.ORACLE_SERVICE }}
      run: |
        echo "Attempting to connect to: $ORACLE_USER@$ORACLE_HOST:$ORACLE_PORT/$ORACLE_SERVICE"
        $(pwd)/sqlcl/bin/sql $ORACLE_USER/$ORACLE_PASSWORD@"(description=(address=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))" @f105/install.sql
