name: APEX Deployment

on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install SQLcl
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip default-jre
        wget https://download.oracle.com/otn_software/java/sqldeveloper/sqlcl-latest.zip
        unzip sqlcl-latest.zip
        echo "$(pwd)/sqlcl/bin" >> $GITHUB_PATH  # Updated path addition method
        
    - name: Verify SQLcl installation
      run: |
        echo "SQLcl path: $(which sql || echo 'Not found')"
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v
        
    - name: Verify install script exists
      run: |
        ls -la f105/install.sql
        if [ ! -f "f105/install.sql" ]; then
          echo "Error: install.sql not found at f105/install.sql"
          exit 1
        fi
        
    - name: Run SQL Query with Proper Output
      run: |
        ${GITHUB_WORKSPACE}/sqlcl/bin/sql -v $ORACLE_USER/$ORACLE_PASSWORD@"(description=(protocol=tcp)(host=$ORACLE_HOST)(port=$ORACLE_PORT))(connect_data=(service_name=$ORACLE_SERVICE)))" <<EOF > sql_output.log
        set feedback on
        set echo on
        set sqlformat ansiconsole
        set serveroutput on size unlimited
        WHENEVER SQLERROR EXIT SQL.SQLCODE
        
        -- Query with forced formatting
        SELECT 'CURRENT_DATE: ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD HH24:MI:SS') AS output FROM DUAL;
        
        -- Ensure output is flushed
        COMMIT;
        EXIT;
        EOF
    
        # Verify log content
        echo "---- SQL OUTPUT LOG CONTENTS ----"
        cat sql_output.log
        echo "---- END LOG ----"
    
    - name: Upload Log
      uses: actions/upload-artifact@v4
      with:
        name: sql-results
        path: sql_output.log
